language: node_js
node_js:
  - '8'
branches:
  only:
  - master
cache:
  directories:
  - node_modules
addons:
  ssh_known_hosts: 47.94.80.19
script:
  - yarn install
  - yarn run test
deploy:
  # deploy master to production
  - provider: script
    script: openssl aes-256-cbc -K $encrypted_8badaf691acc_key -iv $encrypted_8badaf691acc_iv -in id_rsa.enc -out ~/.ssh/id_rsa -d && chmod 600 ~/.ssh/id_rsa && ssh travis@47.94.80.19 'cd ~/zookdoor/ZukBoard && git pull && cnpm install && npm run build && ENABLE_NODE_LOG=YES pm2 restart ecosystem.config.js --env testing'
    on:
      branch: master
