language: node_js
node_js:
- '8'
branchs:
  only:
  - master
cache:
  directories:
  - node_modules
addons:
  ssh_known_hosts: 47.94.80.19
install:
- npm install
before_install:
- openssl aes-256-cbc -K $encrypted_8badaf691acc_key -iv $encrypted_8badaf691acc_iv
  -in deploy_rsa.enc -out ~/.ssh/deploy_rsa -d
- chmod 600 ~/.ssh/deploy_rsa
after_success:
- ssh travis@47.94.80.19 'cd ~/zookdoor/ZukBoard && git pull && cnpm install &&  npm
  run build && ENABLE_NODE_LOG=YES pm2 start ecosystem.config.js --env testing'
