language: node_js
node_js:
- '10'
branches:
  only:
  - master
cache:
  directories:
  - node_modules
script:
- yarn install
- yarn run test
deploy:
  provider: heroku
  app: zukboard-lucifer1004
  api_key:
    secure: epmc3kwwnKElPayKxPNZLVTPC0FRT+8Nadi4Dae/e82Z5FnP8tKDr6A9KAkgBjVJJbvsMCZl/wJt/yVSz7Kg8Xn1i0Lbs+eVq4n78cGjDv1U2krCebWCIiI8yHRc/d8z/gVI3dCYRjMP9qtDa3cufJxXJmXtqbZCV52j63CBiGJ4Fd+RRrxuOrkoUkDaWdzPiu0qVQKCz6Cuuzp5PyqLDrUq5LxWAzmiGzklKN5Flxg3Uvf2kSWt77XFHR2xNq317YUORoT57ranuQPajfNtEVhS28M1B0KuoxAq/nwns0giADfZn7swCtLYXmnmsJoD9SccZW+tHpuHD/fyapsYD5MaFxxTlhwuowFPksQn9/yNExuyDqs7+RIru47lCkWar9965ijYcESwONEArqlmpnEYq06HWki5AN0V14rycnn7RE6vpENE3zV2aIoQ6LP0ZlE3HtvSzzQLCinTHumrZjmBp86DYIHfqpfnLUN6xnn9UJ2xLYyZqYASqsyEUU7SaYqZ8CuQXioZaF1m4yPd7cfgBm/wCFYwGFzZtGKo9lGdE0ZYoHZBHIVUUCHl028Vgm6NGAMqLjiM3YC0jacpvl4ESQQtmVRipLan4ql+CA990reQGUXCq8mpBsY1/YXEEKSgdJ1SrW61xFC359FopKOHEo9daIzW3DEQub2cdew=
  on:
    branch: master
